apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
namespace: hello-gitops
images:
- name: hello-gitops
  newName: cxtsiacr.azurecr.io/wannabe_obs_director
  newTag: ffc035991bab3bf4ef37398d03e638d2b1c69ec5
