apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
namespace: hello-gitops
images:
- name: hello-gitops
  newName: cxtsiacr.azurecr.io/wannabe_obs_director
  newTag: b324e1914af3da90ba4354bba567271f5989e9a0
